CREATE TABLE `signature_artifact_upload_intents` (
  `id` varchar(36) NOT NULL DEFAULT (uuid()),
  `legacy_convex_id` varchar(255),
  `firm_id` varchar(36) NOT NULL,
  `user_id` varchar(36) NOT NULL,
  `document_id` varchar(36) NOT NULL,
  `envelope_id` varchar(36),
  `original_file_name` varchar(255) NOT NULL,
  `declared_mime_type` varchar(255) NOT NULL,
  `declared_size_bytes` bigint NOT NULL,
  `expected_sha256` varchar(255),
  `actual_sha256` varchar(255),
  `quarantine_key` varchar(255) NOT NULL,
  `protected_key` varchar(255),
  `status` enum('pending','uploaded','scanning','promoted','rejected','expired') NOT NULL DEFAULT 'pending',
  `expires_at` timestamp(3) NOT NULL,
  `uploaded_at` timestamp(3) DEFAULT NULL,
  `completed_at` timestamp(3) DEFAULT NULL,
  `failure_code` varchar(255),
  `failure_details` longtext,
  `created_at` timestamp(3) NOT NULL DEFAULT (now()),
  `updated_at` timestamp(3) NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` timestamp(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `signature_artifact_upload_intents_legacy_convex_id_unique` UNIQUE (`legacy_convex_id`),
  UNIQUE KEY `signature_artifact_intents_quarantine_unique` (`quarantine_key`),
  KEY `signature_artifact_intents_owner_idx` (`firm_id`,`user_id`,`document_id`),
  KEY `signature_artifact_intents_status_idx` (`firm_id`,`status`,`expires_at`),
  CONSTRAINT `signature_artifact_intents_firm_fk` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE,
  CONSTRAINT `signature_artifact_intents_user_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `signature_artifact_intents_document_fk` FOREIGN KEY (`document_id`) REFERENCES `documents` (`id`) ON DELETE CASCADE,
  CONSTRAINT `signature_artifact_intents_envelope_fk` FOREIGN KEY (`envelope_id`) REFERENCES `signature_envelopes` (`id`) ON DELETE CASCADE
);
