/**
 * Stub for Convex generated API.
 *
 * When you run `npx convex dev` this file is auto-generated by Convex.
 * This stub allows the app to compile for local UI preview without a running
 * Convex backend. All queries / mutations will be undefined at runtime.
 */

// eslint-disable-next-line no-undef
export const api = new Proxy(
  {},
  {
    get(_target, prop) {
      return new Proxy(
        {},
        {
          get(_t, method) {
            return `${String(prop)}.${String(method)}`;
          },
        },
      );
    },
  },
);
