import fs from "node:fs/promises";
import path from "node:path";
import type { DomainMigrationReport } from "./types";
import { DOC_MIGRATION_DIR, EXCEPTIONS_CSV, RECONCILIATION_REPORT } from "./types";
import type { ReconcileException } from "./reconcile";
import {
  detailsFromReport,
  type ReconciliationDetails,
} from "./reconciliation-details";

export async function appendExceptionsCsv(exceptions: ReconcileException[]) {
  if (exceptions.length === 0) return;
  await fs.mkdir(DOC_MIGRATION_DIR, { recursive: true });
  const exists = await fs
    .access(EXCEPTIONS_CSV)
    .then(() => true)
    .catch(() => false);
  let content = "";
  if (!exists) {
    content += "domain,table,id,type,reason,sourceValue,targetValue,recordedAt\n";
  }
  const recordedAt = new Date().toISOString();
  for (const ex of exceptions) {
    content += [
      csv(ex.domain),
      csv(ex.table),
      csv(ex.id || ""),
      csv(ex.type),
      csv(ex.reason),
      csv(JSON.stringify(ex.sourceValue ?? "")),
      csv(JSON.stringify(ex.targetValue ?? "")),
      csv(recordedAt),
    ].join(",");
    content += "\n";
  }
  await fs.appendFile(EXCEPTIONS_CSV, content, "utf8");
}

export async function appendReconciliationReport(input: {
  domain: string;
  command: string;
  dryRun?: boolean;
  report: DomainMigrationReport;
  notes?: string[];
  /** When omitted, derived from report (counts / missing IDs / FK). */
  details?: ReconciliationDetails;
}) {
  await fs.mkdir(DOC_MIGRATION_DIR, { recursive: true });
  const exists = await fs
    .access(RECONCILIATION_REPORT)
    .then(() => true)
    .catch(() => false);
  const details = input.details ?? detailsFromReport(input.report);
  const lines: string[] = [];
  if (!exists) {
    lines.push("# Migration reconciliation report");
    lines.push("");
    lines.push(
      "Generated by `npm run migration`. Each run appends a section covering counts, missing IDs, FK integrity, financial totals (when applicable), and file SHA-256 (when applicable).",
    );
    lines.push("");
  }
  lines.push(`## ${input.domain} — ${input.command}${input.dryRun ? " (dry-run)" : ""}`);
  lines.push("");
  lines.push(`- Recorded at: \`${new Date().toISOString()}\``);
  lines.push(`- Passed: **${input.report.reconciliation.passed ? "yes" : "no"}**`);
  lines.push(`- Exceptions: ${input.report.exceptions.length}`);
  lines.push("");

  lines.push("### Counts");
  lines.push("");
  lines.push("| Table | Source | Target | Match |");
  lines.push("| --- | ---: | ---: | --- |");
  if (details.counts.length === 0) {
    lines.push("| _(none)_ | 0 | 0 | n/a |");
  } else {
    for (const row of details.counts) {
      lines.push(
        `| ${row.table} | ${row.source} | ${row.target} | ${row.match ? "yes" : "**no**"} |`,
      );
    }
  }
  lines.push("");

  lines.push("### Missing IDs");
  lines.push("");
  if (details.missingIds.length === 0) {
    lines.push("- None");
  } else {
    for (const row of details.missingIds.slice(0, 100)) {
      lines.push(
        `- \`${row.table}\` / \`${row.id}\`${row.reason ? ` — ${row.reason}` : ""}`,
      );
    }
    if (details.missingIds.length > 100) {
      lines.push(`- …and ${details.missingIds.length - 100} more (see data-exceptions.csv)`);
    }
  }
  lines.push("");

  lines.push("### FK integrity");
  lines.push("");
  lines.push(`- Status: **${details.fkIntegrity.status}**`);
  if (details.fkIntegrity.issues.length === 0) {
    lines.push("- No FK-related exceptions");
  } else {
    for (const issue of details.fkIntegrity.issues.slice(0, 50)) {
      lines.push(
        `- \`${issue.table}\`${issue.id ? ` (${issue.id})` : ""} — ${issue.reason}`,
      );
    }
    if (details.fkIntegrity.issues.length > 50) {
      lines.push(`- …and ${details.fkIntegrity.issues.length - 50} more`);
    }
  }
  lines.push("");

  if (details.financialTotals) {
    lines.push("### Financial totals");
    lines.push("");
    lines.push("| Metric | Source | Target | Match |");
    lines.push("| --- | ---: | ---: | --- |");
    for (const row of details.financialTotals) {
      lines.push(
        `| ${row.metric} | ${row.source} | ${row.target} | ${row.match ? "yes" : "**no**"} |`,
      );
    }
    lines.push("");
  }

  if (details.fileSha256) {
    lines.push("### File SHA-256");
    lines.push("");
    lines.push("| Storage ID | Expected | Actual | Status | Match |");
    lines.push("| --- | --- | --- | --- | --- |");
    if (details.fileSha256.length === 0) {
      lines.push("| _(none)_ | — | — | — | n/a |");
    } else {
      for (const row of details.fileSha256) {
        lines.push(
          `| \`${row.storageId}\` | \`${shortHash(row.expectedSha256)}\` | \`${shortHash(row.actualSha256)}\` | ${row.status} | ${row.match ? "yes" : "**no**"} |`,
        );
      }
    }
    lines.push("");
  }

  if (input.report.exceptions.length > 0 && !details.missingIds.length) {
    lines.push("### Exceptions");
    lines.push("");
    for (const ex of input.report.exceptions.slice(0, 50)) {
      lines.push(`- \`${ex.table}\` ${ex.id ? `(${ex.id}) ` : ""}— ${ex.reason}`);
    }
    if (input.report.exceptions.length > 50) {
      lines.push(`- …and ${input.report.exceptions.length - 50} more (see data-exceptions.csv)`);
    }
    lines.push("");
  }

  if (input.notes?.length) {
    lines.push("### Notes");
    lines.push("");
    for (const note of input.notes) lines.push(`- ${note}`);
    lines.push("");
  }
  await fs.appendFile(RECONCILIATION_REPORT, `${lines.join("\n")}\n`, "utf8");
}

function shortHash(value: string | null) {
  if (!value) return "—";
  return value.length > 16 ? `${value.slice(0, 12)}…` : value;
}

function csv(value: string) {
  return `"${value.replace(/"/g, '""')}"`;
}

export function defaultExportPathForDomain(domain: string) {
  const candidates = [
    path.resolve(process.cwd(), "exports", domain),
    path.resolve(process.cwd(), "exports"),
    path.resolve(process.cwd(), "tests", "fixtures", `convex-${domain}-export`),
  ];
  return candidates[0]!;
}
